apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-user
        image: olayigbadeolawale/udagram-api-feed:v2
        env:
          - name: POSTGRES_USERNAME
            value: postgres
          - name: POSTGRES_PASSWORD
            value: Pilot500
          - name: POSTGRES_HOST
            value: eks.cvcomreuoz2p.us-east-1.rds.amazonaws.com
          - name: AWS_BUCKET
            value: microservicesola
          - name: AWS_REGION
            value: us-east-1
          - name: AWS_PROFILE
            value: default
          - name: JWT_SECRET
            value: testing
          - name: URL
            value: http://localhost:8100
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m