language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel --no-cache
  - docker tag udagram-api-feed olayigbadeolawale/udagram-api-feed:v2
  - docker tag udagram-api-user olayigbadeolawale/udagram-api-user:v2
  - docker tag udagram-frontend:v1 olayigbadeolawale/udagram-frontend:v2
  - docker tag reverseproxy olayigbadeolawale/reverseproxy:v2

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push olayigbadeolawale/udagram-api-feed:v2
  - docker push olayigbadeolawale/udagram-api-user:v2
  - docker push olayigbadeolawale/udagram-frontend:v2
  - docker push olayigbadeolawale/reverseproxy:v2
