language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed olayigbadeolawale/udagram-api-feed:v3
  - docker tag udagram-api-user olayigbadeolawale/udagram-api-user:v3
  - docker tag udagram-frontend:local olayigbadeolawale/udagram-frontend:v3
  - docker tag reverseproxy olayigbadeolawale/reverseproxy:v3

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push olayigbadeolawale/udagram-api-feed:v3
  - docker push olayigbadeolawale/udagram-api-user:v3
  - docker push olayigbadeolawale/udagram-frontend:v3
  - docker push olayigbadeolawale/reverseproxy:v3
