# Sample secret

apiVersion: v1
kind: Secret
metadata:
  name: aws-secret # Name of the secret
  namespace: default # Namespace of the secret
data:
  providerAccessKeyId: QVNJQVhDSjZDNDJSUFpPUU5TVUc= # AWS access key id (base64 encoded)
  providerSecretAccessKey: US9Cd0U5bzIvcHUvbE9aZWZhK09Sc0x1akpzb0dJWW5qVEoyWU1GNQ== # AWS secret access key (base64 encoded)
### Alternative data keys are:
# accessKeyId: "pqrstu67890" # AWS access key id (base64 encoded)
# secretAccessKey: "abcdef123456" # AWS secret access key (base64 encoded)
type: Opaque
